project_name: "landing-page"
landing_page_path: "landing-page/"
domain: "solyto.app"
docker_user: "solyto"
docker_uid: 1014
docker_gid: 1014
node_env: "production"
node_port: 3001
timezone: "Europe/Berlin"
node_version: "22"
desktop_version: "1.0.11"
mobile_version: "1.0.11"
